import { useState, useEffect, useCallback } from "react";

/* ═══════════════════════════════════════════════════════════
   alTiro — App USUARIO v3 (39 pantallas)
   Modelo cerrado · Journey: Plomería (Jorge Arturo → Iván Lemus)
   Cotización $250 MXN · Servicios $1,200–$1,800
   Tecnológico de Monterrey | Equipo 5
   ═══════════════════════════════════════════════════════════ */

const C={primary:"#1A7A4B",primaryLight:"#E8F5EE",primaryDark:"#0F5C35",accent:"#E8732A",accentLight:"#FFF3EC",bg:"#F7F8FA",white:"#FFFFFF",card:"#FFFFFF",border:"#E8ECF0",text:"#1A1D21",textSec:"#6B7280",textMut:"#9CA3AF",star:"#F59E0B",danger:"#EF4444",dangerLight:"#FEF2F2",success:"#10B981",successLight:"#ECFDF5",gold:"#D97706",goldLight:"#FFFBEB",shadow:"0 2px 12px rgba(0,0,0,0.06)"};

const S={SPLASH:"splash",OB1:"ob1",OB2:"ob2",OB3:"ob3",LOGIN:"login",OTP:"otp",COMPLETE:"complete",HOME:"home",SUBCAT:"subcat",SVC_INFO:"svcInfo",ADDRESS:"address",TECH_LIST:"techList",TECH_PROFILE:"techProfile",SUMMARY:"summary",PAYMENT:"payment",CONFIRM:"confirm",CONFIRM_Q:"confirmQ",ENROUTE:"enroute",ARRIVAL:"arrival",AGREEMENT:"agreement",PROGRESS:"progress",DONE:"done",QUOTE_DELIVERY:"quoteDelivery",QUOTE_EVAL:"quoteEval",SCHEDULE:"schedule",RATING:"rating",RECEIPT:"receipt",RECEIPT_Q:"receiptQ",TIP:"tip",HISTORY:"history",HIST_DETAIL:"histDetail",PROFILE:"profile",EDIT_PROF:"editProf",ADDRESSES:"addresses",PAY_METHODS:"payMethods",FAVORITES:"favorites",USER_REVIEWS:"userReviews",SETTINGS:"settings",HELP:"help",DISPUTE:"dispute",NOTIFS:"notifs"};

const SERVICES_QUOTE=[
  {id:"plomeria",name:"Plomería",icon:"🔧",needsQuote:true},
  {id:"electricidad",name:"Electricista",icon:"⚡",needsQuote:true},
  {id:"electrodomesticos",name:"Reparación de electrodomésticos",icon:"🔌",needsQuote:true},
  {id:"herreria",name:"Herrería",icon:"⚒️",needsQuote:true},
  {id:"carpinteria",name:"Carpintería",icon:"🪚",needsQuote:true},
  {id:"pintura",name:"Pintura",icon:"🎨",needsQuote:true},
];
const SERVICES_STD=[
  {id:"cerrajeria",name:"Cerrajería",icon:"🔑",needsQuote:false},
  {id:"fumigacion",name:"Fumigación",icon:"🧴",needsQuote:false},
  {id:"jardineria",name:"Jardinería",icon:"🌿",needsQuote:false},
];
const ALL_SERVICES=[...SERVICES_QUOTE,...SERVICES_STD];

const SUBCATS={
  plomeria:["Fuga de agua","Destape de drenaje","Instalación de boiler","Reparación de WC","Mantenimiento de cisternas"],
  electricidad:["Corto circuito","Instalación de contactos","Apagones parciales","Cableado nuevo","Panel eléctrico"],
  electrodomesticos:["Lavadora","Refrigerador","Secadora","Microondas","Calentador de agua"],
  herreria:["Portón","Protecciones para ventanas","Barandales","Escaleras metálicas","Soldadura"],
  carpinteria:["Puertas y marcos","Mueble a medida","Reparación de pisos","Closets","Deck de madera"],
  pintura:["Interior de casa completa","Fachada exterior","Habitación individual","Pintura decorativa","Resanado y preparación"],
  cerrajeria:["Apertura de puerta","Cambio de cerradura","Duplicado de llaves","Cerraduras inteligentes"],
  fumigacion:["Cucarachas","Termitas","Roedores","Fumigación general","Alacranes"],
  jardineria:["Poda de árboles","Diseño de jardín","Sistema de riego","Mantenimiento mensual","Césped"],
};

const STD_PRICES={
  cerrajeria:{"Apertura de puerta":1200,"Cambio de cerradura":1400,"Duplicado de llaves":1200,"Cerraduras inteligentes":1800},
  fumigacion:{"Cucarachas":1200,"Termitas":1500,"Roedores":1300,"Fumigación general":1400,"Alacranes":1200},
  jardineria:{"Poda de árboles":1300,"Diseño de jardín":1800,"Sistema de riego":1500,"Mantenimiento mensual":1200,"Césped":1300},
};

const TECHNICIANS=[
  {id:1,name:"Iván Lemus",photo:"👨‍🔧",rating:4.9,jobs:234,specialty:"Plomería · Electricista",certs:["CONOCER EC0586","Rotoplas Certificado"],distance:"3.2 km",eta:"25 min",bio:"12 años de experiencia en plomería residencial e industrial. Especialista en detección y reparación de fugas.",portfolio:8,responseTime:"< 15 min"},
  {id:2,name:"Roberto Sánchez",photo:"👷",rating:4.7,jobs:189,specialty:"Plomería · Herrería",certs:["CONOCER EC0586"],distance:"4.8 km",eta:"30 min",bio:"Especialista en instalaciones hidráulicas y trabajos de herrería.",portfolio:6,responseTime:"< 20 min"},
  {id:3,name:"Miguel Ángel Torres",photo:"🧑‍🎨",rating:4.8,jobs:156,specialty:"Pintura · Carpintería",certs:["Comex Certificado"],distance:"5.1 km",eta:"35 min",bio:"Pintor profesional con acabados de alta calidad.",portfolio:12,responseTime:"< 10 min"},
  {id:4,name:"Ana Victoria López",photo:"👩‍🔧",rating:4.6,jobs:98,specialty:"Electricista · Electrodomésticos",certs:["CFE Autorizado"],distance:"2.9 km",eta:"20 min",bio:"Ingeniera eléctrica certificada.",portfolio:5,responseTime:"< 25 min"},
  {id:5,name:"Fernando Padilla",photo:"👨‍🏭",rating:4.5,jobs:312,specialty:"Herrería · Carpintería",certs:["CONOCER"],distance:"6.3 km",eta:"40 min",bio:"Más de 15 años de experiencia en hogares de Querétaro.",portfolio:9,responseTime:"< 30 min"},
  {id:6,name:"Diego Luna Ramírez",photo:"🧑‍🔧",rating:4.9,jobs:178,specialty:"Pintura · Jardinería",certs:["Comex Certificado"],distance:"3.7 km",eta:"28 min",bio:"Acabados premium y mantenimiento integral.",portfolio:15,responseTime:"< 12 min"},
];

// ─── DEMO DATA: Plomería journey ───
const DEMO_QUOTE = {
  works:["Reparación de fuga en tubería de cobre","Cambio de válvula de paso dañada","Sellado de juntas y conexiones","Prueba de presión hidráulica"],
  materials:[{n:"Válvula de paso 1/2\"",c:85},{n:"Soldadura y fundente",c:45},{n:"Cinta teflón y sellador",c:30},{n:"Tubo de cobre (tramo)",c:60}],
  labor:1050,
  get materialsTotal(){return this.materials.reduce((a,m)=>a+m.c,0)},
  get subtotal(){return this.labor+this.materialsTotal},
  get commission(){return Math.round(this.subtotal*0.10)},
  get iva(){return Math.round(this.commission*0.16)},
  get total(){return this.subtotal+this.commission+this.iva},
};

const StatusBar=()=>(<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"8px 20px 4px",fontSize:12,fontWeight:600,color:C.text}}><span>9:41</span><div style={{display:"flex",gap:4,alignItems:"center"}}><span style={{fontSize:10}}>●●●●</span><span style={{fontSize:10}}>WiFi</span><span style={{fontSize:11}}>🔋</span></div></div>);
const NavHeader=({title,onBack,rightAction,rightIcon})=>(<div style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"12px 20px",borderBottom:`1px solid ${C.border}`,background:C.white}}><div style={{display:"flex",alignItems:"center",gap:12}}>{onBack&&<button onClick={onBack} style={{background:"none",border:"none",fontSize:20,cursor:"pointer",padding:0,color:C.text}}>←</button>}<span style={{fontSize:18,fontWeight:700,color:C.text}}>{title}</span></div>{rightAction&&<button onClick={rightAction} style={{background:"none",border:"none",fontSize:18,cursor:"pointer",color:C.textSec}}>{rightIcon||"⋯"}</button>}</div>);
const BottomNav=({active,go})=>{const tabs=[{id:"home",l:"Inicio",icon:"🏠",s:S.HOME},{id:"services",l:"Mis servicios",icon:"📋",s:S.HISTORY},{id:"profile",l:"Perfil",icon:"👤",s:S.PROFILE}];return(<div style={{display:"flex",borderTop:`1px solid ${C.border}`,background:C.white,paddingBottom:8}}>{tabs.map(t=>(<button key={t.id} onClick={()=>go(t.s)} style={{flex:1,display:"flex",flexDirection:"column",alignItems:"center",gap:2,padding:"10px 0 4px",background:"none",border:"none",cursor:"pointer",color:active===t.id?C.primary:C.textMut,fontWeight:active===t.id?700:400,fontSize:10}}><span style={{fontSize:20}}>{t.icon}</span><span>{t.l}</span>{active===t.id&&<div style={{width:20,height:3,borderRadius:2,background:C.primary,marginTop:2}}/>}</button>))}</div>);};
const Btn=({children,onClick,v="primary",full=true,sz="md",disabled=false,sx={}})=>{const vs={primary:{background:C.accent,color:C.white},secondary:{background:C.primaryLight,color:C.primary},outline:{background:"transparent",color:C.primary,border:`2px solid ${C.primary}`},danger:{background:C.danger,color:C.white},ghost:{background:"transparent",color:C.textSec},success:{background:C.success,color:C.white},gold:{background:C.gold,color:C.white}};const szs={sm:{padding:"10px 16px",fontSize:13},md:{padding:"14px 24px",fontSize:15},lg:{padding:"18px 32px",fontSize:16}};return <button onClick={disabled?undefined:onClick} style={{border:"none",borderRadius:14,cursor:disabled?"default":"pointer",fontWeight:700,width:full?"100%":"auto",opacity:disabled?0.5:1,fontFamily:"inherit",transition:"all 0.2s",...szs[sz],...vs[v],...sx}}>{children}</button>;};
const Card=({children,onClick,sx={}})=>(<div onClick={onClick} style={{background:C.card,borderRadius:16,padding:16,boxShadow:C.shadow,border:`1px solid ${C.border}`,cursor:onClick?"pointer":"default",transition:"all 0.2s",...sx}}>{children}</div>);
const Stars=({r,size=18,interactive=false,onChange})=>(<div style={{display:"flex",gap:2}}>{[1,2,3,4,5].map(i=>(<span key={i} onClick={()=>interactive&&onChange?.(i)} style={{fontSize:size,cursor:interactive?"pointer":"default",color:i<=r?C.star:"#E5E7EB"}}>{i<=r?"★":"☆"}</span>))}</div>);
const Badge=({children,color=C.primary,bg})=>(<span style={{display:"inline-block",padding:"4px 10px",borderRadius:20,fontSize:11,fontWeight:600,color,background:bg||(color+"18")}}>{children}</span>);
const Input=({label,placeholder,value,icon,multiline})=>(<div style={{marginBottom:16}}>{label&&<label style={{display:"block",fontSize:13,fontWeight:600,color:C.textSec,marginBottom:6}}>{label}</label>}<div style={{display:"flex",alignItems:multiline?"flex-start":"center",border:`1.5px solid ${C.border}`,borderRadius:12,padding:"12px 14px",background:C.white,gap:8}}>{icon&&<span style={{fontSize:16}}>{icon}</span>}{multiline?<textarea placeholder={placeholder} defaultValue={value} style={{border:"none",outline:"none",flex:1,fontSize:14,fontFamily:"inherit",color:C.text,background:"transparent",resize:"none",minHeight:60}}/>:<input placeholder={placeholder} defaultValue={value} style={{border:"none",outline:"none",flex:1,fontSize:14,fontFamily:"inherit",color:C.text,background:"transparent"}}/>}</div></div>);
const Dots=({c,t})=>(<div style={{display:"flex",gap:8,justifyContent:"center"}}>{Array.from({length:t},(_,i)=>(<div key={i} style={{width:i===c?24:8,height:8,borderRadius:4,background:i===c?C.primary:"#D1D5DB",transition:"all 0.3s"}}/>))}</div>);
const Section=({children,action,onAction})=>(<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}><span style={{fontSize:16,fontWeight:700,color:C.text}}>{children}</span>{action&&<button onClick={onAction} style={{background:"none",border:"none",color:C.primary,fontSize:13,fontWeight:600,cursor:"pointer"}}>{action}</button>}</div>);

export default function AlTiroUserApp(){
  const[screen,setScreen]=useState(S.SPLASH);const[hist,setHist]=useState([]);const[tab,setTab]=useState("home");
  const[selService,setSelService]=useState(null);const[selSubcat,setSelSubcat]=useState(null);const[selTech,setSelTech]=useState(null);
  const[rating,setRating]=useState(0);const[tipAmt,setTipAmt]=useState(0);const[agreementOk,setAgreementOk]=useState(false);
  const[payMethod,setPayMethod]=useState(null);const[selTags,setSelTags]=useState([]);const[scheduleDate,setScheduleDate]=useState(null);
  const[executeNow,setExecuteNow]=useState(false);

  const go=useCallback((s)=>{setHist(h=>[...h,screen]);setScreen(s);if(s===S.HOME)setTab("home");if(s===S.HISTORY)setTab("services");if(s===S.PROFILE)setTab("profile");},[screen]);
  const back=useCallback(()=>{if(hist.length>0){const p=hist[hist.length-1];setHist(h=>h.slice(0,-1));setScreen(p);if(p===S.HOME)setTab("home");if(p===S.HISTORY)setTab("services");if(p===S.PROFILE)setTab("profile");}},[hist]);
  const reset=()=>{setSelService(null);setSelSubcat(null);setSelTech(null);setRating(0);setTipAmt(0);setAgreementOk(false);setPayMethod(null);setSelTags([]);setScheduleDate(null);setExecuteNow(false);setHist([]);setScreen(S.HOME);setTab("home");};

  useEffect(()=>{if(screen===S.SPLASH){const t=setTimeout(()=>setScreen(S.OB1),2000);return()=>clearTimeout(t);}},[screen]);

  const showNav=[S.HOME,S.HISTORY,S.HIST_DETAIL,S.PROFILE,S.EDIT_PROF,S.ADDRESSES,S.PAY_METHODS,S.FAVORITES,S.USER_REVIEWS,S.SETTINGS,S.HELP,S.DISPUTE,S.NOTIFS].includes(screen);
  const tech=selTech||TECHNICIANS[0];const svc=selService||ALL_SERVICES[0];const sub=selSubcat||"Servicio general";
  const isQuote=svc.needsQuote;const visitCost=250;const visitIVA=Math.round(visitCost*0.16);const visitTotal=visitCost+visitIVA;
  const stdPrice=(!isQuote&&STD_PRICES[svc.id])?(STD_PRICES[svc.id][sub]||1300):1300;
  const stdComm=Math.round(stdPrice*0.10);const stdIVA=Math.round(stdComm*0.16);const totalStd=stdPrice+stdComm+stdIVA;
  const Q=DEMO_QUOTE;

  // ═══ ONBOARDING (7) ═══
  const renderSplash=()=>(<div style={{flex:1,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",background:`linear-gradient(145deg,${C.primary},${C.primaryDark})`,overflow:"hidden",position:"relative"}}><div style={{position:"absolute",top:-40,right:-40,width:160,height:160,borderRadius:"50%",background:"rgba(255,255,255,0.06)"}}/><div style={{fontSize:48,marginBottom:8}}>🐦</div><div style={{fontSize:36,fontWeight:800,color:C.white,letterSpacing:-1}}>alTiro</div><div style={{fontSize:14,color:"rgba(255,255,255,0.8)",marginTop:4}}>Servicios a domicilio verificados</div></div>);

  const renderOB=(step)=>{const sl=[{icon:"🔍",title:"Técnicos verificados a tu alcance",desc:"Todos nuestros técnicos son seleccionados y verificados por alTiro. Revisa perfiles, certificaciones y reseñas reales.",bg:C.primaryLight},{icon:"📋",title:"Cada servicio, su proceso justo",desc:"Servicios técnicos como plomería incluyen cotización a domicilio. Servicios como cerrajería y fumigación tienen tarifas fijas.",bg:C.accentLight},{icon:"🛡️",title:"Pago seguro, trabajo garantizado",desc:"Tu dinero queda protegido hasta que confirmes el trabajo. Acuerdo digital firmado por ambas partes.",bg:C.goldLight}][step];return(<div style={{flex:1,display:"flex",flexDirection:"column",background:C.white}}><div style={{flex:1,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:"40px 32px",background:sl.bg,margin:16,borderRadius:24}}><div style={{fontSize:72,marginBottom:24}}>{sl.icon}</div><div style={{fontSize:24,fontWeight:800,color:C.text,textAlign:"center",marginBottom:12}}>{sl.title}</div><div style={{fontSize:15,color:C.textSec,textAlign:"center",lineHeight:1.6}}>{sl.desc}</div></div><div style={{padding:"20px 24px 32px"}}><Dots c={step} t={3}/><div style={{marginTop:20,display:"flex",gap:12}}>{step>0&&<Btn v="ghost" full={false} onClick={()=>setScreen(["ob1","ob2","ob3"][step-1])}>Atrás</Btn>}<Btn onClick={()=>{if(step<2)setScreen(["ob1","ob2","ob3"][step+1]);else go(S.LOGIN);}}>{step<2?"Siguiente":"Comenzar"}</Btn></div></div></div>);};

  const renderLogin=()=>(<div style={{flex:1,display:"flex",flexDirection:"column",background:C.white,padding:24}}><div style={{marginTop:20,marginBottom:32}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:8}}><span style={{fontSize:28}}>🐦</span><span style={{fontSize:24,fontWeight:800,color:C.primary}}>alTiro</span></div><div style={{fontSize:26,fontWeight:800,marginBottom:4}}>Bienvenido</div><div style={{fontSize:14,color:C.textSec}}>Servicios a domicilio verificados</div></div><Input label="Número de teléfono" placeholder="442 123 4567" icon="📱"/><Btn onClick={()=>go(S.OTP)}>Continuar con teléfono</Btn><div style={{textAlign:"center",margin:"20px 0",color:C.textMut,fontSize:13}}>— o continúa con —</div><div style={{display:"flex",gap:12}}><Btn v="outline" onClick={()=>go(S.OTP)}>🔵 Google</Btn><Btn v="outline" onClick={()=>go(S.OTP)}>⚫ Apple</Btn></div><div style={{marginTop:"auto",textAlign:"center",fontSize:11,color:C.textMut}}>Al continuar aceptas los <span style={{color:C.primary,fontWeight:600}}>Términos</span> y <span style={{color:C.primary,fontWeight:600}}>Privacidad</span></div></div>);
  const renderOTP=()=>(<div style={{flex:1,background:C.white}}><NavHeader title="Verificación" onBack={back}/><div style={{padding:24}}><div style={{fontSize:20,fontWeight:700,marginBottom:8}}>Ingresa el código</div><div style={{fontSize:14,color:C.textSec,marginBottom:32}}>Enviamos un SMS al <strong>442 •••• 4567</strong></div><div style={{display:"flex",gap:12,justifyContent:"center",marginBottom:32}}>{[3,8,1,5].map((n,i)=>(<div key={i} style={{width:52,height:56,borderRadius:12,border:`2px solid ${C.primary}`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:22,fontWeight:700}}>{n}</div>))}</div><Btn onClick={()=>go(S.COMPLETE)}>Verificar</Btn></div></div>);
  const renderComplete=()=>(<div style={{flex:1,background:C.white,overflowY:"auto"}}><NavHeader title="Completa tu perfil" onBack={back}/><div style={{padding:16}}><div style={{display:"flex",justifyContent:"center",marginBottom:20}}><div style={{width:80,height:80,borderRadius:40,background:C.primaryLight,display:"flex",alignItems:"center",justifyContent:"center",fontSize:36,border:`3px dashed ${C.primary}`}}>📷</div></div><Input label="Nombre completo" value="Jorge Arturo Ruelas Mejía" icon="👤"/><Input label="Correo electrónico" placeholder="jorge.ruelas@email.com" icon="✉️"/><Input label="Dirección principal" value="Av. Universidad 100, Juriquilla, Qro." icon="🏠"/><Btn onClick={()=>{setHist([]);setScreen(S.HOME);setTab("home");}}>Crear cuenta</Btn></div></div>);

  // ═══ HOME ═══
  const renderHome=()=>(<div style={{flex:1,background:C.bg,overflowY:"auto"}}>
    <div style={{background:`linear-gradient(135deg,${C.primary},${C.primaryDark})`,padding:"20px 20px 28px",borderRadius:"0 0 28px 28px"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}><div><div style={{display:"flex",alignItems:"center",gap:6,marginBottom:4}}><span style={{fontSize:18}}>🐦</span><span style={{fontSize:18,fontWeight:800,color:C.white}}>alTiro</span></div><div style={{fontSize:22,fontWeight:800,color:C.white}}>Hola, Jorge Arturo 👋</div><div style={{fontSize:13,color:"rgba(255,255,255,0.7)"}}>¿Qué necesitas hoy?</div></div><button onClick={()=>go(S.NOTIFS)} style={{width:40,height:40,borderRadius:12,background:"rgba(255,255,255,0.15)",border:"none",fontSize:18,cursor:"pointer",color:C.white,position:"relative"}}>🔔<div style={{position:"absolute",top:6,right:6,width:8,height:8,borderRadius:4,background:C.accent}}/></button></div></div>
    <div style={{padding:"20px 16px"}}>
      <Section>Servicios técnicos</Section>
      <Card sx={{marginBottom:12,background:C.goldLight,border:`1px solid ${C.gold}20`,padding:12}}><div style={{fontSize:12,color:C.gold,fontWeight:600}}>📋 Incluyen visita de cotización ($250 MXN). El técnico evalúa y entrega presupuesto.</div></Card>
      <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:10,marginBottom:24}}>{SERVICES_QUOTE.map(s=>(<Card key={s.id} onClick={()=>{setSelService(s);go(S.SUBCAT);}} sx={{textAlign:"center",padding:12,cursor:"pointer",position:"relative"}}><div style={{fontSize:26,marginBottom:4}}>{s.icon}</div><div style={{fontSize:11,fontWeight:600,color:C.text,lineHeight:1.2}}>{s.name}</div><div style={{position:"absolute",top:4,right:4}}><Badge color={C.gold}>📋</Badge></div></Card>))}</div>
      <Section>Servicios con tarifa fija</Section>
      <Card sx={{marginBottom:12,background:C.successLight,border:`1px solid ${C.success}20`,padding:12}}><div style={{fontSize:12,color:C.primaryDark,fontWeight:600}}>⚡ Precio fijo. El técnico llega y resuelve en una sola visita.</div></Card>
      <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:10,marginBottom:20}}>{SERVICES_STD.map(s=>(<Card key={s.id} onClick={()=>{setSelService(s);go(S.SUBCAT);}} sx={{textAlign:"center",padding:12,cursor:"pointer",position:"relative"}}><div style={{fontSize:26,marginBottom:4}}>{s.icon}</div><div style={{fontSize:11,fontWeight:600,color:C.text,lineHeight:1.2}}>{s.name}</div><div style={{position:"absolute",top:4,right:4}}><Badge color={C.success}>⚡</Badge></div></Card>))}</div>
      <Card sx={{background:C.accentLight,border:`1px solid ${C.accent}30`}}><div style={{display:"flex",alignItems:"center",gap:10}}><span style={{fontSize:22}}>🎉</span><div><div style={{fontSize:14,fontWeight:700,color:C.accent}}>¡Primera vez? 20% OFF</div><div style={{fontSize:12,color:C.textSec}}>En tu primer servicio con alTiro</div></div></div></Card>
    </div>
  </div>);

  // ═══ BOOKING ═══
  const renderSubcat=()=>(<div style={{flex:1,background:C.bg,overflowY:"auto"}}><NavHeader title={svc.name} onBack={back}/><div style={{padding:16}}>
    <Card sx={{marginBottom:12,background:isQuote?C.goldLight:C.successLight,border:`1px solid ${isQuote?C.gold:C.success}20`,padding:12}}><div style={{fontSize:12,fontWeight:600,color:isQuote?C.gold:C.primaryDark}}>{isQuote?`📋 Servicio con cotización. El técnico visitará y evaluará ($${visitCost} MXN).`:"⚡ Tarifa fija. Precio definido, sin sorpresas."}</div></Card>
    <div style={{fontSize:14,color:C.textSec,marginBottom:12}}>Selecciona el tipo de servicio:</div>
    {(SUBCATS[svc.id]||[]).map((sc,i)=>(<Card key={i} onClick={()=>{setSelSubcat(sc);go(S.SVC_INFO);}} sx={{marginBottom:8,display:"flex",alignItems:"center",justifyContent:"space-between",cursor:"pointer"}}><div style={{display:"flex",alignItems:"center",gap:12}}><span style={{fontSize:18}}>{svc.icon}</span><span style={{fontSize:14,fontWeight:600}}>{sc}</span></div><div style={{display:"flex",alignItems:"center",gap:8}}>{!isQuote&&STD_PRICES[svc.id]&&<span style={{fontSize:13,fontWeight:800,color:C.primary}}>${STD_PRICES[svc.id][sc]} MXN</span>}<span style={{color:C.textMut}}>›</span></div></Card>))}
  </div></div>);

  const renderSvcInfo=()=>(<div style={{flex:1,background:C.bg,overflowY:"auto"}}><NavHeader title="Tu servicio" onBack={back}/><div style={{padding:16}}>
    <Card sx={{marginBottom:16,textAlign:"center",padding:20}}><div style={{fontSize:36,marginBottom:8}}>{svc.icon}</div><div style={{fontSize:18,fontWeight:800}}>{svc.name}</div><div style={{fontSize:14,color:C.textSec,marginTop:4}}>{sub}</div></Card>
    {isQuote?(<Card sx={{marginBottom:16,border:`2px solid ${C.gold}40`}}><div style={{display:"flex",gap:14}}><div style={{width:52,height:52,borderRadius:16,background:C.goldLight,display:"flex",alignItems:"center",justifyContent:"center",fontSize:26}}>📋</div><div style={{flex:1}}><div style={{fontSize:16,fontWeight:700,color:C.gold}}>Servicio con cotización</div><div style={{fontSize:13,color:C.textSec,lineHeight:1.5,marginTop:6}}>Un técnico verificado por alTiro visitará tu domicilio para evaluar el problema y entregarte un presupuesto detallado.</div><div style={{marginTop:10,padding:10,background:C.goldLight,borderRadius:10}}><div style={{fontSize:12,fontWeight:700,color:C.gold,marginBottom:6}}>¿Cómo funciona?</div>{[`1. Selecciona un técnico`,`2. Visita de evaluación ($${visitCost} MXN)`,`3. Recibe presupuesto detallado`,`4. Acepta y agenda — o ejecuta en el momento`].map((s,i)=>(<div key={i} style={{fontSize:12,color:C.textSec,padding:"3px 0"}}>{s}</div>))}</div></div></div></Card>)
    :(<Card sx={{marginBottom:16,border:`2px solid ${C.success}40`}}><div style={{display:"flex",gap:14}}><div style={{width:52,height:52,borderRadius:16,background:C.successLight,display:"flex",alignItems:"center",justifyContent:"center",fontSize:26}}>⚡</div><div style={{flex:1}}><div style={{fontSize:16,fontWeight:700,color:C.success}}>Tarifa fija</div><div style={{fontSize:13,color:C.textSec,lineHeight:1.5,marginTop:6}}>Precio estandarizado. El técnico llega y resuelve en una sola visita.</div><div style={{marginTop:10,padding:10,background:C.successLight,borderRadius:10}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontSize:12,fontWeight:700,color:C.primaryDark}}>Tarifa fija:</span><span style={{fontSize:18,fontWeight:800,color:C.primary}}>${stdPrice} MXN</span></div><div style={{fontSize:11,color:C.textMut,marginTop:4}}>+ comisión e IVA</div></div></div></div></Card>)}
    <Btn onClick={()=>go(S.ADDRESS)}>Continuar</Btn>
  </div></div>);

  const renderAddress=()=>(<div style={{flex:1,background:C.bg,overflowY:"auto"}}><NavHeader title="Dirección y horario" onBack={back}/><div style={{padding:16}}><div style={{height:120,borderRadius:16,background:`linear-gradient(135deg,${C.primaryLight},#D1FAE5)`,marginBottom:16,display:"flex",alignItems:"center",justifyContent:"center"}}><span style={{fontSize:32}}>📍</span></div><Input label="Dirección" value="Av. Universidad 100, Juriquilla, Qro." icon="🏠"/><Input label="Referencia" placeholder="Casa blanca con portón negro" icon="📝"/><Input label="Fecha" value="Hoy, 15 de Marzo 2026" icon="📅"/><Input label="Horario" value="10:00 AM - 12:00 PM" icon="🕐"/>{isQuote&&<Card sx={{background:C.goldLight,border:`1px solid ${C.gold}30`,marginBottom:16,padding:12}}><div style={{fontSize:12,color:C.gold,fontWeight:600}}>📋 Visita de evaluación · ${visitCost} MXN + IVA</div></Card>}<Btn onClick={()=>go(S.TECH_LIST)}>Ver técnicos disponibles</Btn></div></div>);

  const renderTechList=()=>(<div style={{flex:1,background:C.bg,overflowY:"auto"}}><NavHeader title="Técnicos disponibles" onBack={back}/><div style={{display:"flex",gap:8,padding:"8px 16px"}}>{["⭐ Mejor rating","📍 Más cerca","🔧 Más experiencia"].map((f,i)=>(<button key={i} style={{padding:"8px 12px",borderRadius:20,border:`1.5px solid ${i===0?C.primary:C.border}`,background:i===0?C.primaryLight:C.white,fontSize:11,fontWeight:600,color:i===0?C.primary:C.textSec,cursor:"pointer",whiteSpace:"nowrap"}}>{f}</button>))}</div><div style={{padding:"8px 16px"}}>{TECHNICIANS.map(t=>(<Card key={t.id} onClick={()=>{setSelTech(t);go(S.TECH_PROFILE);}} sx={{marginBottom:10,cursor:"pointer"}}><div style={{display:"flex",gap:12}}><div style={{width:52,height:52,borderRadius:16,background:C.primaryLight,display:"flex",alignItems:"center",justifyContent:"center",fontSize:24}}>{t.photo}</div><div style={{flex:1}}><div style={{display:"flex",justifyContent:"space-between"}}><div style={{fontSize:15,fontWeight:700}}>{t.name}</div><div style={{fontSize:16,fontWeight:800,color:isQuote?C.gold:C.primary}}>{isQuote?`$${visitCost}`:`$${stdPrice}`}</div></div><div style={{fontSize:12,color:C.textMut}}>{t.specialty} · {t.distance}</div><div style={{display:"flex",alignItems:"center",gap:6,marginTop:4}}><Stars r={Math.floor(t.rating)} size={12}/><span style={{fontSize:12,fontWeight:600}}>{t.rating}</span><span style={{fontSize:11,color:C.textMut}}>({t.jobs})</span><Badge color={C.textSec}>⏱ {t.eta}</Badge></div></div></div></Card>))}</div></div>);

  const renderTechProfile=()=>(<div style={{flex:1,background:C.bg,overflowY:"auto"}}><NavHeader title="Perfil del técnico" onBack={back}/><div style={{padding:16}}><Card sx={{marginBottom:16,textAlign:"center",padding:24}}><div style={{width:72,height:72,borderRadius:20,background:C.primaryLight,display:"flex",alignItems:"center",justifyContent:"center",fontSize:36,margin:"0 auto 8px"}}>{tech.photo}</div><div style={{fontSize:20,fontWeight:800}}>{tech.name}</div><div style={{fontSize:13,color:C.textMut}}>{tech.specialty}</div><div style={{display:"flex",justifyContent:"center",alignItems:"center",gap:6,marginTop:6}}><Stars r={Math.floor(tech.rating)} size={16}/><span style={{fontWeight:700}}>{tech.rating}</span><span style={{fontSize:12,color:C.textMut}}>({tech.jobs} trabajos)</span></div></Card><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8,marginBottom:16}}>{[{v:tech.jobs,l:"Trabajos"},{v:tech.responseTime,l:"Respuesta"},{v:tech.portfolio,l:"Portafolio"}].map((s,i)=>(<Card key={i} sx={{textAlign:"center",padding:12}}><div style={{fontSize:16,fontWeight:800,color:C.primary}}>{s.v}</div><div style={{fontSize:10,color:C.textMut}}>{s.l}</div></Card>))}</div><Card sx={{marginBottom:16}}><Section>Sobre mí</Section><div style={{fontSize:13,color:C.textSec,lineHeight:1.6}}>{tech.bio}</div></Card><Card sx={{marginBottom:16}}><Section>Certificaciones</Section><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{tech.certs.map(c=>(<Badge key={c} color={C.primary}>{c}</Badge>))}</div></Card><Card sx={{marginBottom:16}}><Section>Portafolio</Section><div style={{display:"flex",gap:8}}>{Array.from({length:4},(_,i)=>(<div key={i} style={{width:64,height:64,borderRadius:10,background:[C.primaryLight,C.accentLight,C.goldLight,"#F0F4FF"][i],display:"flex",alignItems:"center",justifyContent:"center",fontSize:20}}>🖼️</div>))}</div></Card><Btn onClick={()=>go(S.SUMMARY)}>{isQuote?`Solicitar cotización — $${visitCost} MXN`:`Solicitar servicio — $${stdPrice} MXN`}</Btn></div></div>);

  const renderSummary=()=>(<div style={{flex:1,background:C.bg,overflowY:"auto"}}><NavHeader title="Resumen" onBack={back}/><div style={{padding:16}}>
    {isQuote?<Card sx={{marginBottom:12,background:C.goldLight,border:`1px solid ${C.gold}30`}}><div style={{fontSize:13,fontWeight:700,color:C.gold}}>📋 Cotización a domicilio</div></Card>:<Card sx={{marginBottom:12,background:C.successLight,border:`1px solid ${C.success}30`}}><div style={{fontSize:13,fontWeight:700,color:C.primaryDark}}>⚡ Tarifa fija — ${stdPrice} MXN</div></Card>}
    <Card sx={{marginBottom:16}}><div style={{display:"flex",alignItems:"center",gap:12}}><div style={{width:48,height:48,borderRadius:14,background:C.primaryLight,display:"flex",alignItems:"center",justifyContent:"center",fontSize:22}}>{svc.icon}</div><div><div style={{fontSize:16,fontWeight:700}}>{svc.name} — {sub}</div><div style={{fontSize:12,color:C.textMut}}>📅 Hoy, 15 Mar 2026 · 10:00 AM</div><div style={{fontSize:12,color:C.textMut}}>📍 Av. Universidad 100, Juriquilla</div></div></div></Card>
    <Card sx={{marginBottom:16}}><div style={{display:"flex",alignItems:"center",gap:12}}><div style={{width:44,height:44,borderRadius:12,background:C.primaryLight,display:"flex",alignItems:"center",justifyContent:"center",fontSize:20}}>{tech.photo}</div><div><div style={{fontSize:14,fontWeight:700}}>{tech.name}</div><div style={{display:"flex",alignItems:"center",gap:4}}><Stars r={Math.floor(tech.rating)} size={11}/><span style={{fontSize:12}}>{tech.rating}</span></div></div></div></Card>
    <Section>Describe el problema</Section>
    <textarea defaultValue={isQuote&&svc.id==="plomeria"?"Hay una fuga de agua debajo del fregadero de la cocina. Ya cerré la llave de paso pero sigue goteando.":""} placeholder="Describe el problema o servicio que necesitas..." style={{width:"100%",height:70,border:`1.5px solid ${C.border}`,borderRadius:12,padding:12,fontSize:13,fontFamily:"inherit",resize:"none",outline:"none",marginBottom:12,boxSizing:"border-box"}}/>
    <div style={{display:"flex",gap:8,marginBottom:16}}>{[0,1,2].map(i=>(<div key={i} style={{width:72,height:72,borderRadius:12,border:`2px dashed ${i===0?C.primary:C.border}`,background:i===0?C.primaryLight:C.bg,display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer"}}><span style={{fontSize:i===0?11:20,color:i===0?C.primary:C.textMut}}>{i===0?"📷 Foto":"+"}</span></div>))}</div>
    <Btn onClick={()=>go(S.PAYMENT)}>Continuar al pago</Btn>
  </div></div>);

  const renderPayment=()=>(<div style={{flex:1,background:C.bg,overflowY:"auto"}}><NavHeader title="Método de pago" onBack={back}/><div style={{padding:16}}>
    {isQuote&&<Card sx={{marginBottom:12,background:C.goldLight,border:`1px solid ${C.gold}30`,padding:12}}><div style={{fontSize:12,color:C.gold,fontWeight:600}}>📋 Solo se cobra la visita de evaluación: ${visitCost} MXN + IVA</div></Card>}
    {[{id:"visa",label:"Visa •••• 4532",icon:"💳"},{id:"mc",label:"Mastercard •••• 8891",icon:"💳"},{id:"spei",label:"SPEI / Transferencia",icon:"🏦"},{id:"oxxo",label:"Pago en OXXO",icon:"🏪"}].map(m=>(<Card key={m.id} onClick={()=>setPayMethod(m.id)} sx={{marginBottom:8,display:"flex",alignItems:"center",justifyContent:"space-between",cursor:"pointer",border:payMethod===m.id?`2px solid ${C.primary}`:`1px solid ${C.border}`}}><div style={{display:"flex",alignItems:"center",gap:12}}><span style={{fontSize:20}}>{m.icon}</span><span style={{fontSize:14,fontWeight:600}}>{m.label}</span></div><div style={{width:20,height:20,borderRadius:10,border:`2px solid ${payMethod===m.id?C.primary:C.border}`,background:payMethod===m.id?C.primary:C.white,display:"flex",alignItems:"center",justifyContent:"center"}}>{payMethod===m.id&&<span style={{color:C.white,fontSize:10}}>✓</span>}</div></Card>))}
    <Card sx={{marginBottom:16,marginTop:12}}>
      {isQuote?<>{[{l:"Visita de cotización",v:`$${visitCost}.00`},{l:"IVA (16%)",v:`$${visitIVA}.00`}].map((r,i)=>(<div key={i} style={{display:"flex",justifyContent:"space-between",padding:"4px 0",fontSize:13,color:C.textSec}}><span>{r.l}</span><span style={{fontWeight:600}}>{r.v}</span></div>))}<div style={{display:"flex",justifyContent:"space-between",padding:"10px 0 0",marginTop:8,borderTop:`2px solid ${C.gold}`,fontSize:16,fontWeight:800,color:C.gold}}><span>Total</span><span>${visitTotal} MXN</span></div></>
      :<>{[{l:"Servicio (tarifa fija)",v:`$${stdPrice}.00`},{l:"Comisión (10%)",v:`$${stdComm}.00`},{l:"IVA",v:`$${stdIVA}.00`}].map((r,i)=>(<div key={i} style={{display:"flex",justifyContent:"space-between",padding:"4px 0",fontSize:13,color:C.textSec}}><span>{r.l}</span><span style={{fontWeight:600}}>{r.v}</span></div>))}<div style={{display:"flex",justifyContent:"space-between",padding:"10px 0 0",marginTop:8,borderTop:`2px solid ${C.primary}`,fontSize:16,fontWeight:800,color:C.primary}}><span>Total</span><span>${totalStd} MXN</span></div></>}
    </Card>
    <Btn onClick={()=>go(isQuote?S.CONFIRM_Q:S.CONFIRM)} disabled={!payMethod}>Confirmar y pagar</Btn>
  </div></div>);

  const renderConfirm=()=>(<div style={{flex:1,background:C.bg,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:24}}><div style={{width:88,height:88,borderRadius:44,background:C.successLight,display:"flex",alignItems:"center",justifyContent:"center",fontSize:44,marginBottom:16}}>✅</div><div style={{fontSize:22,fontWeight:800,textAlign:"center",marginBottom:4}}>¡Servicio confirmado!</div><div style={{fontSize:14,color:C.textSec,textAlign:"center"}}>{svc.name} — {sub}</div><div style={{fontSize:13,color:C.textMut}}>con {tech.name}</div><Card sx={{width:"100%",marginTop:20,marginBottom:16,textAlign:"center"}}><div style={{fontSize:13,color:C.textMut}}>Total</div><div style={{fontSize:28,fontWeight:800,color:C.primary}}>${totalStd} MXN</div><div style={{fontSize:12,color:C.textMut}}>📅 Hoy · 10:00 AM</div></Card><Btn onClick={()=>go(S.ENROUTE)}>Seguir mi servicio</Btn></div>);

  const renderConfirmQ=()=>(<div style={{flex:1,background:C.bg,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:24}}><div style={{width:88,height:88,borderRadius:44,background:C.goldLight,display:"flex",alignItems:"center",justifyContent:"center",fontSize:44,marginBottom:16}}>📋</div><div style={{fontSize:22,fontWeight:800,textAlign:"center",marginBottom:4}}>¡Cotización agendada!</div><div style={{fontSize:14,color:C.textSec,textAlign:"center"}}>{svc.name} — {sub}</div><div style={{fontSize:13,color:C.textMut}}>con {tech.name}</div><Card sx={{width:"100%",marginTop:20,marginBottom:16}}><div style={{textAlign:"center",marginBottom:8}}><div style={{fontSize:13,color:C.textMut}}>Visita de evaluación</div><div style={{fontSize:28,fontWeight:800,color:C.gold}}>${visitTotal} MXN</div></div><div style={{borderTop:`1px solid ${C.border}`,paddingTop:8,fontSize:12,color:C.textSec,textAlign:"center"}}>El técnico evaluará y entregará presupuesto detallado.</div></Card><Btn onClick={()=>go(S.ENROUTE)}>Seguir mi cotización</Btn></div>);

  // ═══ DURING ═══
  const renderEnroute=()=>(<div style={{flex:1,background:C.bg,display:"flex",flexDirection:"column"}}><div style={{height:220,background:`linear-gradient(135deg,${C.primaryLight},#D1FAE5)`,position:"relative"}}><div style={{position:"absolute",top:16,left:16}}><button onClick={back} style={{width:36,height:36,borderRadius:10,background:C.white,border:"none",fontSize:16,cursor:"pointer",boxShadow:C.shadow}}>←</button></div><div style={{position:"absolute",top:"35%",left:"20%",fontSize:28}}>🚗</div><div style={{position:"absolute",top:"55%",right:"20%",fontSize:24}}>📍</div><div style={{position:"absolute",bottom:12,left:12,right:12,background:C.white,borderRadius:12,padding:"10px 14px",display:"flex",justifyContent:"space-between",alignItems:"center",boxShadow:C.shadow}}><div><div style={{fontSize:12,fontWeight:600}}>{tech.name} va en camino</div><div style={{fontSize:11,color:C.textMut}}>Llegada estimada</div></div><div style={{fontSize:22,fontWeight:800,color:C.primary}}>{tech.eta}</div></div></div><div style={{padding:16,flex:1}}><Card sx={{marginBottom:12}}><div style={{display:"flex",alignItems:"center",gap:12}}><div style={{width:44,height:44,borderRadius:12,background:C.primaryLight,display:"flex",alignItems:"center",justifyContent:"center",fontSize:20}}>{tech.photo}</div><div style={{flex:1}}><div style={{fontSize:15,fontWeight:700}}>{tech.name}</div><div style={{fontSize:12,color:C.textMut}}>{svc.name} · {isQuote?"Cotización":"Servicio"}</div></div></div></Card>{isQuote&&<Card sx={{marginBottom:12,background:C.goldLight,border:`1px solid ${C.gold}30`,padding:12}}><div style={{fontSize:12,color:C.gold,fontWeight:600}}>📋 Visita de evaluación — Presupuesto detallado</div></Card>}<Btn onClick={()=>go(S.ARRIVAL)}>El técnico ha llegado</Btn></div></div>);

  const renderArrival=()=>(<div style={{flex:1,background:C.bg,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:24}}><div style={{width:96,height:96,borderRadius:24,background:C.successLight,display:"flex",alignItems:"center",justifyContent:"center",fontSize:48,marginBottom:16}}>🏠</div><div style={{fontSize:20,fontWeight:800,textAlign:"center",marginBottom:4}}>{tech.name} ha llegado</div><div style={{fontSize:14,color:C.textSec,textAlign:"center",marginBottom:28}}>Confirma que el técnico está en tu domicilio</div><div style={{width:"100%",maxWidth:300}}><Btn onClick={()=>go(isQuote?S.QUOTE_DELIVERY:S.AGREEMENT)}>✓ Confirmar llegada</Btn><div style={{height:8}}/><Btn v="ghost" onClick={back}>No ha llegado aún</Btn></div></div>);

  // ROUTE A — Fixed rate
  const renderAgreement=()=>(<div style={{flex:1,background:C.bg,overflowY:"auto"}}><NavHeader title="Acuerdo de servicio"/><div style={{background:C.accentLight,padding:"10px 16px",fontSize:12,color:C.accent,fontWeight:600}}>⚠️ Ambas partes deben aceptar antes de iniciar</div><div style={{padding:16}}><Card sx={{marginBottom:16}}><Section>Trabajos a realizar</Section>{["Ejecución del servicio solicitado","Verificación de resultado","Limpieza del área"].map((w,i)=>(<div key={i} style={{display:"flex",alignItems:"center",gap:10,padding:"8px 0",borderBottom:i<2?`1px solid ${C.border}`:"none"}}><span style={{color:C.success}}>✓</span><span style={{fontSize:13}}>{w}</span></div>))}</Card><Card sx={{marginBottom:16}}>{[{l:"Tarifa fija",v:`$${stdPrice}.00`},{l:"Comisión (10%)",v:`$${stdComm}.00`},{l:"IVA",v:`$${stdIVA}.00`}].map((r,i)=>(<div key={i} style={{display:"flex",justifyContent:"space-between",padding:"4px 0",fontSize:13,color:C.textSec}}><span>{r.l}</span><span style={{fontWeight:600}}>{r.v}</span></div>))}<div style={{display:"flex",justifyContent:"space-between",padding:"10px 0 0",marginTop:8,borderTop:`2px solid ${C.primary}`,fontSize:16,fontWeight:800,color:C.primary}}><span>Total</span><span>${totalStd} MXN</span></div></Card><div onClick={()=>setAgreementOk(!agreementOk)} style={{display:"flex",alignItems:"center",gap:10,marginBottom:16,cursor:"pointer"}}><div style={{width:24,height:24,borderRadius:8,border:`2px solid ${agreementOk?C.primary:C.border}`,background:agreementOk?C.primary:C.white,display:"flex",alignItems:"center",justifyContent:"center"}}>{agreementOk&&<span style={{color:C.white,fontSize:12}}>✓</span>}</div><span style={{fontSize:13}}>Acepto el acuerdo y autorizo el cargo</span></div><Btn onClick={()=>go(S.PROGRESS)} disabled={!agreementOk}>✍️ Firmar y autorizar</Btn></div></div>);

  // ROUTE B — Quote (PLOMERÍA JOURNEY)
  const renderQuoteDelivery=()=>(<div style={{flex:1,background:C.bg,overflowY:"auto"}}><NavHeader title="Cotización recibida"/><div style={{padding:16}}>
    <Card sx={{marginBottom:16,background:C.goldLight,border:`1px solid ${C.gold}30`,textAlign:"center",padding:20}}><div style={{fontSize:36,marginBottom:8}}>📋</div><div style={{fontSize:18,fontWeight:800,color:C.gold}}>Cotización de {tech.name}</div><div style={{fontSize:13,color:C.textSec,marginTop:4}}>{svc.name} — {sub}</div></Card>
    <Card sx={{marginBottom:16}}><Section>Diagnóstico</Section><div style={{fontSize:13,color:C.textSec,lineHeight:1.6}}>Tras evaluar el problema, el técnico ha identificado los siguientes trabajos:</div></Card>
    <Card sx={{marginBottom:16}}><Section>Trabajos propuestos</Section>{Q.works.map((w,i)=>(<div key={i} style={{display:"flex",alignItems:"center",gap:10,padding:"8px 0",borderBottom:i<Q.works.length-1?`1px solid ${C.border}`:"none"}}><span style={{color:C.primary}}>•</span><span style={{fontSize:13}}>{w}</span></div>))}</Card>
    <Card sx={{marginBottom:16}}><Section>Materiales</Section>{Q.materials.map((m,j)=>(<div key={j} style={{display:"flex",justifyContent:"space-between",padding:"6px 0",fontSize:13,borderBottom:j<Q.materials.length-1?`1px solid ${C.border}`:"none"}}><span>{m.n}</span><span style={{fontWeight:600,color:C.primary}}>${m.c}</span></div>))}</Card>
    <Card sx={{marginBottom:16}}>
      {[{l:"Mano de obra",v:`$${Q.labor}.00`},{l:"Materiales",v:`$${Q.materialsTotal}.00`},{l:"Comisión alTiro (10%)",v:`$${Q.commission}.00`},{l:"IVA",v:`$${Q.iva}.00`}].map((r,i)=>(<div key={i} style={{display:"flex",justifyContent:"space-between",padding:"4px 0",fontSize:13,color:C.textSec}}><span>{r.l}</span><span style={{fontWeight:600}}>{r.v}</span></div>))}
      <div style={{display:"flex",justifyContent:"space-between",padding:"10px 0 0",marginTop:8,borderTop:`2px solid ${C.gold}`,fontSize:16,fontWeight:800,color:C.gold}}><span>Total del servicio</span><span>${Q.total} MXN</span></div>
      <div style={{fontSize:12,color:C.textMut,marginTop:4}}>⏱ Tiempo estimado: 1.5–2 horas</div>
    </Card>
    <Btn onClick={()=>go(S.QUOTE_EVAL)}>Confirmar que recibí la cotización</Btn>
  </div></div>);

  const renderQuoteEval=()=>(<div style={{flex:1,background:C.bg,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:24}}>
    <div style={{width:88,height:88,borderRadius:22,background:C.successLight,display:"flex",alignItems:"center",justifyContent:"center",fontSize:44,marginBottom:16}}>✅</div>
    <div style={{fontSize:20,fontWeight:800,textAlign:"center",marginBottom:4}}>Evaluación completada</div>
    <div style={{fontSize:14,color:C.textSec,textAlign:"center"}}>Cotización entregada por {tech.name}</div>
    <Card sx={{width:"100%",marginTop:16,marginBottom:16}}>
      <div style={{display:"flex",justifyContent:"space-between",fontSize:13,color:C.textSec,marginBottom:4}}><span>Cargo de visita</span><span style={{fontWeight:700,color:C.gold}}>${visitTotal} MXN</span></div>
      <div style={{display:"flex",justifyContent:"space-between",fontSize:13,color:C.textSec}}><span>Cotización servicio</span><span style={{fontWeight:700,color:C.primary}}>${Q.total} MXN</span></div>
    </Card>
    <Btn onClick={()=>go(S.RATING)}>Calificar la visita</Btn>
  </div>);

  // POST-SERVICE
  const renderRating=()=>{const tags=["Puntual","Limpio","Buen precio","Profesional","Amable","Eficiente"];return(<div style={{flex:1,background:C.bg,overflowY:"auto"}}><NavHeader title="Califica al técnico"/><div style={{padding:16}}><div style={{textAlign:"center",marginBottom:20}}><div style={{width:64,height:64,borderRadius:18,background:C.primaryLight,display:"flex",alignItems:"center",justifyContent:"center",fontSize:32,margin:"0 auto 8px"}}>{tech.photo}</div><div style={{fontSize:17,fontWeight:700}}>{tech.name}</div></div><div style={{display:"flex",justifyContent:"center",marginBottom:20}}><Stars r={rating} size={36} interactive onChange={setRating}/></div><div style={{display:"flex",flexWrap:"wrap",gap:8,justifyContent:"center",marginBottom:20}}>{tags.map(tag=>{const s=selTags.includes(tag);return <button key={tag} onClick={()=>setSelTags(s?selTags.filter(t=>t!==tag):[...selTags,tag])} style={{padding:"8px 16px",borderRadius:20,border:`1.5px solid ${s?C.primary:C.border}`,background:s?C.primaryLight:C.white,fontSize:13,fontWeight:600,color:s?C.primary:C.textSec,cursor:"pointer"}}>{tag}</button>;})}</div><textarea placeholder="Escribe una reseña (opcional)..." style={{width:"100%",height:70,border:`1.5px solid ${C.border}`,borderRadius:12,padding:12,fontSize:13,fontFamily:"inherit",resize:"none",outline:"none",marginBottom:16,boxSizing:"border-box"}}/><Btn onClick={()=>go(isQuote&&!executeNow?S.RECEIPT_Q:S.RECEIPT)} disabled={rating===0}>Enviar calificación</Btn></div></div>);};

  const renderReceipt=()=>{const rTotal=executeNow?Q.total:totalStd;const rRows=executeNow?[{l:"Servicio",v:`${svc.name} — ${sub}`},{l:"Técnico",v:tech.name},{l:"Fecha",v:"15 Mar 2026, 10:00 AM"},{l:"Mano de obra",v:`$${Q.labor}.00`},{l:"Materiales",v:`$${Q.materialsTotal}.00`},{l:"Comisión (10%)",v:`$${Q.commission}.00`},{l:"IVA",v:`$${Q.iva}.00`}]:[{l:"Servicio",v:`${svc.name} — ${sub}`},{l:"Técnico",v:tech.name},{l:"Fecha",v:"15 Mar 2026, 10:00 AM"},{l:"Tarifa",v:`$${stdPrice}.00`},{l:"Comisión",v:`$${stdComm}.00`},{l:"IVA",v:`$${stdIVA}.00`}];return(<div style={{flex:1,background:C.bg,overflowY:"auto"}}><NavHeader title="Recibo digital"/><div style={{padding:16}}><Card sx={{marginBottom:16,textAlign:"center",padding:24}}><div style={{fontSize:28}}>🧾</div><div style={{fontSize:20,fontWeight:800,color:C.primary,marginTop:8}}>Recibo de servicio</div><div style={{fontSize:12,color:C.textMut,marginTop:4}}>#ALT-2026-001530</div></Card><Card sx={{marginBottom:16}}>{rRows.map((r,i)=>(<div key={i} style={{display:"flex",justifyContent:"space-between",padding:"6px 0",fontSize:13,borderBottom:i<rRows.length-1?`1px solid ${C.border}`:"none"}}><span style={{color:C.textSec}}>{r.l}</span><span style={{fontWeight:600}}>{r.v}</span></div>))}<div style={{display:"flex",justifyContent:"space-between",padding:"12px 0 0",marginTop:8,borderTop:`2px solid ${C.primary}`,fontSize:16,fontWeight:800,color:C.primary}}><span>Total pagado</span><span>${rTotal} MXN</span></div></Card><Btn v="secondary" onClick={()=>go(S.TIP)}>Continuar</Btn></div></div>);};

  const renderReceiptQ=()=>(<div style={{flex:1,background:C.bg,overflowY:"auto"}}><NavHeader title="Recibo de cotización"/><div style={{padding:16}}><Card sx={{marginBottom:16,textAlign:"center",padding:24,background:C.goldLight,border:`1px solid ${C.gold}30`}}><div style={{fontSize:28}}>📋</div><div style={{fontSize:20,fontWeight:800,color:C.gold,marginTop:8}}>Recibo de evaluación</div><div style={{fontSize:12,color:C.textMut,marginTop:4}}>#ALT-Q-2026-000892</div></Card><Card sx={{marginBottom:16}}>{[{l:"Tipo",v:"Evaluación a domicilio"},{l:"Servicio evaluado",v:`${svc.name} — ${sub}`},{l:"Técnico",v:tech.name},{l:"Visita",v:`$${visitCost}.00`},{l:"IVA",v:`$${visitIVA}.00`}].map((r,i)=>(<div key={i} style={{display:"flex",justifyContent:"space-between",padding:"6px 0",fontSize:13,borderBottom:i<4?`1px solid ${C.border}`:"none"}}><span style={{color:C.textSec}}>{r.l}</span><span style={{fontWeight:600}}>{r.v}</span></div>))}<div style={{display:"flex",justifyContent:"space-between",padding:"12px 0 0",marginTop:8,borderTop:`2px solid ${C.gold}`,fontSize:16,fontWeight:800,color:C.gold}}><span>Total</span><span>${visitTotal} MXN</span></div></Card><Card sx={{marginBottom:16,background:C.primaryLight,border:`1px solid ${C.primary}20`,padding:12}}><div style={{fontSize:13,color:C.primaryDark}}><strong>Cotización:</strong> ${Q.total} MXN por el servicio completo.</div></Card><Btn onClick={()=>go(S.TIP)}>Continuar</Btn></div></div>);

  const renderTip=()=>(<div style={{flex:1,background:C.bg,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:24}}><div style={{fontSize:44,marginBottom:12}}>💚</div><div style={{fontSize:20,fontWeight:800,marginBottom:4}}>¿Dejar propina?</div><div style={{fontSize:14,color:C.textSec,marginBottom:20}}>El 100% va directo al técnico</div><div style={{display:"flex",gap:10,marginBottom:20}}>{[0,30,50,100].map(a=>(<button key={a} onClick={()=>setTipAmt(a)} style={{width:64,height:64,borderRadius:16,border:`2px solid ${tipAmt===a?C.primary:C.border}`,background:tipAmt===a?C.primaryLight:C.white,display:"flex",alignItems:"center",justifyContent:"center",fontSize:a===0?12:16,fontWeight:700,color:tipAmt===a?C.primary:C.textSec,cursor:"pointer"}}>{a===0?"No":"$"+a}</button>))}</div><div style={{width:"100%",maxWidth:300}}><Btn onClick={()=>{if(isQuote&&!executeNow){go(S.SCHEDULE);}else{reset();}}}>{isQuote&&!executeNow?"Continuar":"Volver al inicio"}</Btn></div></div>);

  // ★ SCHEDULE — with "execute now" option
  const renderSchedule=()=>(<div style={{flex:1,background:C.bg,overflowY:"auto"}}><NavHeader title="Agendar servicio"/><div style={{padding:16}}>
    <Card sx={{marginBottom:16,background:C.goldLight,border:`1px solid ${C.gold}30`,textAlign:"center",padding:20}}><div style={{fontSize:28,marginBottom:8}}>📋 → ⚡</div><div style={{fontSize:16,fontWeight:800,color:C.gold}}>Cotización #{" "}ALT-Q-2026-000892</div><div style={{fontSize:13,color:C.textSec,marginTop:4}}>De {tech.name} por ${Q.total} MXN</div></Card>
    <div style={{fontSize:15,fontWeight:700,marginBottom:12}}>¿Cómo quieres proceder?</div>

    {/* EXECUTE NOW option */}
    <Card onClick={()=>{setScheduleDate("now");setExecuteNow(true);}} sx={{marginBottom:12,cursor:"pointer",border:scheduleDate==="now"?`2px solid ${C.accent}`:`2px solid ${C.accent}40`,background:scheduleDate==="now"?C.accentLight:C.white}}>
      <div style={{display:"flex",alignItems:"center",gap:12}}><div style={{width:48,height:48,borderRadius:14,background:C.accentLight,display:"flex",alignItems:"center",justifyContent:"center",fontSize:22}}>⚡</div><div style={{flex:1}}><div style={{fontSize:15,fontWeight:700,color:C.accent}}>Ejecutar reparación ahora</div><div style={{fontSize:12,color:C.textSec}}>El técnico ya está aquí. Iniciar el servicio de inmediato.</div></div></div>
    </Card>

    <div style={{fontSize:13,color:C.textMut,textAlign:"center",margin:"12px 0"}}>— o agenda para otro día —</div>

    {[{id:"18mar",d:"Miércoles 18 de Marzo",h:"9:00 AM - 11:00 AM"},{id:"19mar",d:"Jueves 19 de Marzo",h:"10:00 AM - 12:00 PM"},{id:"20mar",d:"Viernes 20 de Marzo",h:"8:00 AM - 10:00 AM"}].map(o=>(<Card key={o.id} onClick={()=>{setScheduleDate(o.id);setExecuteNow(false);}} sx={{marginBottom:10,cursor:"pointer",border:scheduleDate===o.id?`2px solid ${C.primary}`:`1px solid ${C.border}`}}><div style={{display:"flex",alignItems:"center",gap:12}}><div style={{width:44,height:44,borderRadius:12,background:C.primaryLight,display:"flex",alignItems:"center",justifyContent:"center",fontSize:18}}>📅</div><div><div style={{fontSize:14,fontWeight:700}}>{o.d}</div><div style={{fontSize:12,color:C.textMut}}>{o.h}</div></div></div></Card>))}

    <Card sx={{marginBottom:16,marginTop:8}}><div style={{display:"flex",justifyContent:"space-between",fontSize:14,fontWeight:700}}><span>Total del servicio</span><span style={{color:C.primary}}>${Q.total} MXN</span></div><div style={{fontSize:12,color:C.textMut,marginTop:4}}>Técnico: {tech.name} · Presupuesto aprobado</div></Card>
    <Btn onClick={()=>{if(executeNow){setAgreementOk(false);go(S.AGREEMENT);}else{reset();}}} disabled={!scheduleDate}>{executeNow?"Confirmar y ejecutar ahora":"✓ Confirmar y agendar"}</Btn>
    <div style={{height:8}}/><Btn v="ghost" onClick={reset}>Decidir después</Btn>
  </div></div>);

  // SERVICE PROGRESS (shared for both routes)
  const renderProgress=()=>(<div style={{flex:1,background:C.bg,overflowY:"auto"}}><NavHeader title="Servicio en progreso"/><div style={{padding:16}}><Card sx={{marginBottom:16}}><div style={{display:"flex",alignItems:"center",gap:12,marginBottom:12}}><div style={{width:44,height:44,borderRadius:12,background:C.primaryLight,display:"flex",alignItems:"center",justifyContent:"center",fontSize:20}}>{tech.photo}</div><div style={{flex:1}}><div style={{fontSize:15,fontWeight:700}}>{tech.name}</div><div style={{fontSize:12,color:C.textMut}}>Trabajando en tu servicio</div></div><Badge color={C.success}>En progreso</Badge></div><div style={{textAlign:"center",padding:"12px 0",background:C.bg,borderRadius:12}}><div style={{fontSize:32,fontWeight:800,color:C.primary}}>00:45:22</div><div style={{fontSize:12,color:C.textMut}}>Tiempo transcurrido</div></div></Card><Card sx={{marginBottom:16}}><Section>Progreso</Section>{(executeNow?Q.works:["Ejecución del servicio","Verificación","Limpieza"]).map((w,i,a)=>(<div key={i} style={{display:"flex",alignItems:"center",gap:10,padding:"8px 0"}}><span style={{color:i<a.length-1?C.success:C.textMut}}>{i<a.length-1?"✅":"⏳"}</span><span style={{fontSize:13,color:i<a.length-1?C.textMut:C.text,textDecoration:i<a.length-1?"line-through":"none"}}>{w}</span></div>))}</Card><Btn onClick={()=>go(S.DONE)}>El técnico terminó el trabajo</Btn></div></div>);

  const renderDone=()=>(<div style={{flex:1,background:C.bg,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:24}}><div style={{width:88,height:88,borderRadius:22,background:C.successLight,display:"flex",alignItems:"center",justifyContent:"center",fontSize:44,marginBottom:16}}>✅</div><div style={{fontSize:22,fontWeight:800,marginBottom:4}}>¡Servicio completado!</div><div style={{fontSize:14,color:C.textSec}}>{tech.name} terminó el trabajo</div><div style={{fontSize:13,color:C.textMut,marginBottom:24}}>{svc.name} — {sub}</div><Btn onClick={()=>{setRating(0);setSelTags([]);go(S.RATING);}}>Calificar al técnico</Btn></div>);

  // ═══ HISTORY ═══
  const renderHistory=()=>(<div style={{flex:1,background:C.bg,overflowY:"auto"}}><div style={{padding:"16px 16px 8px"}}><div style={{fontSize:22,fontWeight:800}}>Mis servicios</div></div><div style={{padding:"0 16px"}}>{[{type:"Plomería",sub:"Fuga de agua",tech:"Iván Lemus",date:"15 Mar",price:`$${Q.total}`,status:"Completado",icon:"🔧",mode:"quote"},{type:"Cerrajería",sub:"Cambio de cerradura",tech:"Roberto S.",date:"28 Feb",price:"$1,554",status:"Completado",icon:"🔑",mode:"std"},{type:"Jardinería",sub:"Poda de árboles",tech:"Diego L. R.",date:"15 Feb",price:"$1,443",status:"Completado",icon:"🌿",mode:"std"},{type:"Electricista",sub:"Corto circuito",tech:"Ana V. L.",date:"2 Feb",price:"$1,520",status:"Cotización",icon:"⚡",mode:"quote"}].map((s,i)=>(<Card key={i} onClick={()=>go(S.HIST_DETAIL)} sx={{marginBottom:10,cursor:"pointer"}}><div style={{display:"flex",gap:12}}><div style={{width:44,height:44,borderRadius:12,background:C.primaryLight,display:"flex",alignItems:"center",justifyContent:"center",fontSize:20}}>{s.icon}</div><div style={{flex:1}}><div style={{display:"flex",justifyContent:"space-between"}}><span style={{fontSize:14,fontWeight:700}}>{s.type} — {s.sub}</span><span style={{fontSize:14,fontWeight:800,color:C.primary}}>{s.price}</span></div><div style={{fontSize:12,color:C.textMut,marginTop:2}}>{s.tech} · {s.date}</div><div style={{display:"flex",gap:6,marginTop:4}}><Badge color={s.status==="Completado"?C.success:C.gold}>{s.status}</Badge><Badge color={s.mode==="quote"?C.gold:C.success}>{s.mode==="quote"?"📋 Cotización":"⚡ Tarifa fija"}</Badge></div></div></div></Card>))}</div></div>);
  const renderHistDetail=()=>(<div style={{flex:1,background:C.bg,overflowY:"auto"}}><NavHeader title="Detalle" onBack={back}/><div style={{padding:16}}><Card sx={{marginBottom:16,textAlign:"center",padding:20}}><div style={{fontSize:28}}>🔧</div><div style={{fontSize:18,fontWeight:800,marginTop:8}}>Plomería — Fuga de agua</div><div style={{fontSize:13,color:C.textMut}}>Iván Lemus · 15 Mar 2026</div><div style={{fontSize:22,fontWeight:800,color:C.primary,marginTop:8}}>${Q.total} MXN</div><Badge color={C.success}>Completado</Badge></Card><Btn v="secondary" onClick={back}>Volver</Btn></div></div>);

  // ═══ PROFILE ═══
  const renderProfile=()=>(<div style={{flex:1,background:C.bg,overflowY:"auto"}}><div style={{background:C.white,padding:"20px 16px",marginBottom:8}}><div style={{display:"flex",alignItems:"center",gap:14}}><div style={{width:64,height:64,borderRadius:18,background:C.primaryLight,display:"flex",alignItems:"center",justifyContent:"center",fontSize:28}}>👨</div><div style={{flex:1}}><div style={{fontSize:18,fontWeight:800}}>Jorge Arturo Ruelas Mejía</div><div style={{fontSize:13,color:C.textMut}}>jorge.ruelas@email.com</div><div style={{display:"flex",alignItems:"center",gap:4,marginTop:4}}><Stars r={4} size={12}/><span style={{fontSize:12,fontWeight:600}}>4.8</span></div></div><button onClick={()=>go(S.EDIT_PROF)} style={{background:C.bg,border:"none",borderRadius:10,width:36,height:36,fontSize:14,cursor:"pointer"}}>✏️</button></div></div><div style={{padding:"0 16px"}}>{[{icon:"👤",l:"Editar perfil",s:S.EDIT_PROF},{icon:"🏠",l:"Direcciones guardadas",s:S.ADDRESSES},{icon:"💳",l:"Métodos de pago",s:S.PAY_METHODS},{icon:"❤️",l:"Técnicos favoritos",s:S.FAVORITES},{icon:"⭐",l:"Reseñas que he recibido",s:S.USER_REVIEWS},{icon:"⚙️",l:"Configuración",s:S.SETTINGS}].map((item,i)=>(<Card key={i} onClick={()=>go(item.s)} sx={{marginBottom:8,display:"flex",alignItems:"center",justifyContent:"space-between",cursor:"pointer"}}><div style={{display:"flex",alignItems:"center",gap:12}}><span style={{fontSize:18}}>{item.icon}</span><span style={{fontSize:14,fontWeight:600}}>{item.l}</span></div><span style={{color:C.textMut}}>›</span></Card>))}<div style={{height:8}}/>{[{icon:"❓",l:"Centro de ayuda",s:S.HELP},{icon:"🚨",l:"Reportar problema",s:S.DISPUTE}].map((item,i)=>(<Card key={i} onClick={()=>go(item.s)} sx={{marginBottom:8,display:"flex",alignItems:"center",justifyContent:"space-between",cursor:"pointer"}}><div style={{display:"flex",alignItems:"center",gap:12}}><span style={{fontSize:18}}>{item.icon}</span><span style={{fontSize:14,fontWeight:600}}>{item.l}</span></div><span style={{color:C.textMut}}>›</span></Card>))}<div style={{padding:"16px 0"}}><Btn v="ghost" onClick={()=>setScreen(S.LOGIN)}><span style={{color:C.danger}}>Cerrar sesión</span></Btn></div></div></div>);

  const renderEditProf=()=>(<div style={{flex:1,background:C.bg,overflowY:"auto"}}><NavHeader title="Editar perfil" onBack={back}/><div style={{padding:16}}><Input label="Nombre" value="Jorge Arturo Ruelas Mejía" icon="👤"/><Input label="Teléfono" value="442 123 4567" icon="📱"/><Input label="Correo" value="jorge.ruelas@email.com" icon="✉️"/><Btn onClick={back}>Guardar</Btn></div></div>);
  const renderAddresses=()=>(<div style={{flex:1,background:C.bg,overflowY:"auto"}}><NavHeader title="Direcciones" onBack={back}/><div style={{padding:16}}>{["🏠 Casa — Av. Universidad 100, Juriquilla, Qro.","🏢 Oficina — Blvd. Bernardo Quintana 300"].map((a,i)=>(<Card key={i} sx={{marginBottom:8}}><span style={{fontSize:13}}>{a}</span></Card>))}<Card sx={{border:`1.5px dashed ${C.primary}`,background:C.primaryLight,cursor:"pointer"}}><div style={{textAlign:"center",fontSize:14,fontWeight:600,color:C.primary}}>＋ Agregar dirección</div></Card></div></div>);
  const renderPayMethods=()=>(<div style={{flex:1,background:C.bg,overflowY:"auto"}}><NavHeader title="Métodos de pago" onBack={back}/><div style={{padding:16}}>{["💳 Visa •••• 4532","💳 Mastercard •••• 8891","🏦 SPEI"].map((m,i)=>(<Card key={i} sx={{marginBottom:8}}><span style={{fontSize:13}}>{m}</span></Card>))}<Card sx={{border:`1.5px dashed ${C.primary}`,background:C.primaryLight,cursor:"pointer"}}><div style={{textAlign:"center",fontSize:14,fontWeight:600,color:C.primary}}>＋ Agregar método de pago</div></Card></div></div>);
  const renderFavorites=()=>(<div style={{flex:1,background:C.bg,overflowY:"auto"}}><NavHeader title="Técnicos favoritos" onBack={back}/><div style={{padding:16}}>{TECHNICIANS.slice(0,3).map(t=>(<Card key={t.id} sx={{marginBottom:10,display:"flex",alignItems:"center",gap:12}}><div style={{width:44,height:44,borderRadius:12,background:C.primaryLight,display:"flex",alignItems:"center",justifyContent:"center",fontSize:20}}>{t.photo}</div><div style={{flex:1}}><div style={{fontSize:14,fontWeight:700}}>{t.name}</div><div style={{display:"flex",alignItems:"center",gap:4}}><Stars r={Math.floor(t.rating)} size={11}/><span style={{fontSize:12}}>{t.rating}</span></div></div><span style={{color:C.danger,fontSize:18}}>❤️</span></Card>))}</div></div>);
  const renderUserReviews=()=>(<div style={{flex:1,background:C.bg,overflowY:"auto"}}><NavHeader title="Reseñas recibidas" onBack={back}/><div style={{padding:16}}>{[{from:"Iván L.",r:5,text:"Excelente cliente, muy accesible y puntual."},{from:"Miguel Á.",r:5,text:"Casa bien ubicada, buena comunicación."},{from:"Ana V.",r:4,text:"Buen trato durante el servicio."}].map((rev,i)=>(<Card key={i} sx={{marginBottom:10}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:4}}><span style={{fontSize:14,fontWeight:600}}>{rev.from}</span><Stars r={rev.r} size={12}/></div><div style={{fontSize:13,color:C.textSec}}>{rev.text}</div></Card>))}</div></div>);
  const renderSettings=()=>(<div style={{flex:1,background:C.bg,overflowY:"auto"}}><NavHeader title="Configuración" onBack={back}/><div style={{padding:16}}>{["🔔 Notificaciones","🌐 Idioma — Español","🔒 Privacidad (LFPDPPP)","📄 Términos y condiciones","🛡️ Protección PROFECO","ℹ️ Acerca de alTiro v1.0"].map((s,i)=>(<Card key={i} sx={{marginBottom:8}}><span style={{fontSize:13,fontWeight:600}}>{s}</span></Card>))}</div></div>);
  const renderHelp=()=>(<div style={{flex:1,background:C.bg,overflowY:"auto"}}><NavHeader title="Centro de ayuda" onBack={back}/><div style={{padding:16}}><Input placeholder="Buscar..." icon="🔍"/>{["¿Cómo funciona alTiro?","¿Por qué algunos servicios requieren cotización?","¿Cómo se protege mi pago?","¿Qué pasa si no quedo satisfecho?","¿Puedo cancelar un servicio?","¿Los técnicos están verificados?"].map((q,i)=>(<Card key={i} sx={{marginBottom:8,cursor:"pointer"}}><span style={{fontSize:13,fontWeight:600}}>{q}</span></Card>))}</div></div>);
  const renderDispute=()=>(<div style={{flex:1,background:C.bg,overflowY:"auto"}}><NavHeader title="Reportar problema" onBack={back}/><div style={{padding:16}}>{["El técnico no llegó","Trabajo de mala calidad","Cobro incorrecto","Daño a mi propiedad","Comportamiento inapropiado","Otro"].map((p,i)=>(<Card key={i} sx={{marginBottom:8,cursor:"pointer"}}><span style={{fontSize:13,fontWeight:600}}>{p}</span></Card>))}<Input label="Detalle" placeholder="Describe el problema..." multiline/><Btn onClick={back}>Enviar reporte</Btn></div></div>);
  const renderNotifs=()=>(<div style={{flex:1,background:C.bg,overflowY:"auto"}}><NavHeader title="Notificaciones" onBack={back}/><div style={{padding:16}}>{[{t:"Técnico en camino",d:"Iván Lemus va hacia tu domicilio",time:"5 min",u:true},{t:"Cotización lista",d:`Iván Lemus entregó cotización de plomería por $${Q.total}`,time:"2h",u:true},{t:"Servicio completado",d:"Tu servicio de cerrajería fue completado",time:"Ayer",u:false},{t:"¡20% de descuento!",d:"Usa tu cupón en tu próximo servicio",time:"3 días",u:false}].map((n,i)=>(<Card key={i} sx={{marginBottom:8,background:n.u?C.primaryLight:C.white}}><div style={{display:"flex",justifyContent:"space-between"}}><span style={{fontSize:13,fontWeight:700}}>{n.t}</span><span style={{fontSize:11,color:C.textMut}}>{n.time}</span></div><div style={{fontSize:12,color:C.textSec,marginTop:2}}>{n.d}</div></Card>))}</div></div>);

  const R=()=>{switch(screen){
    case S.SPLASH:return renderSplash();case S.OB1:return renderOB(0);case S.OB2:return renderOB(1);case S.OB3:return renderOB(2);
    case S.LOGIN:return renderLogin();case S.OTP:return renderOTP();case S.COMPLETE:return renderComplete();
    case S.HOME:return renderHome();case S.SUBCAT:return renderSubcat();case S.SVC_INFO:return renderSvcInfo();
    case S.ADDRESS:return renderAddress();case S.TECH_LIST:return renderTechList();case S.TECH_PROFILE:return renderTechProfile();
    case S.SUMMARY:return renderSummary();case S.PAYMENT:return renderPayment();case S.CONFIRM:return renderConfirm();case S.CONFIRM_Q:return renderConfirmQ();
    case S.ENROUTE:return renderEnroute();case S.ARRIVAL:return renderArrival();case S.AGREEMENT:return renderAgreement();case S.PROGRESS:return renderProgress();case S.DONE:return renderDone();
    case S.QUOTE_DELIVERY:return renderQuoteDelivery();case S.QUOTE_EVAL:return renderQuoteEval();case S.SCHEDULE:return renderSchedule();
    case S.RATING:return renderRating();case S.RECEIPT:return renderReceipt();case S.RECEIPT_Q:return renderReceiptQ();case S.TIP:return renderTip();
    case S.HISTORY:return renderHistory();case S.HIST_DETAIL:return renderHistDetail();
    case S.PROFILE:return renderProfile();case S.EDIT_PROF:return renderEditProf();case S.ADDRESSES:return renderAddresses();case S.PAY_METHODS:return renderPayMethods();
    case S.FAVORITES:return renderFavorites();case S.USER_REVIEWS:return renderUserReviews();case S.SETTINGS:return renderSettings();
    case S.HELP:return renderHelp();case S.DISPUTE:return renderDispute();case S.NOTIFS:return renderNotifs();
    default:return renderHome();
  }};

  return(<div style={{display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",minHeight:"100vh",background:"#E8ECF0",fontFamily:"'DM Sans',-apple-system,sans-serif",padding:16}}>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet"/>
    <style>{`*{box-sizing:border-box;margin:0;padding:0;}::-webkit-scrollbar{width:0;}button:active{transform:scale(0.97);}input::placeholder,textarea::placeholder{color:${C.textMut};}`}</style>
    <div style={{marginBottom:12,textAlign:"center"}}><div style={{fontSize:12,fontWeight:700,color:C.primary,textTransform:"uppercase",letterSpacing:2}}>alTiro · App Usuario v3</div><div style={{fontSize:11,color:"#9CA3AF"}}><strong>{screen}</strong>{" · "}<button onClick={back} style={{background:"none",border:"none",color:C.primary,cursor:"pointer",fontWeight:600,fontSize:11}}>← Atrás</button>{" "}<button onClick={reset} style={{background:"none",border:"none",color:C.accent,cursor:"pointer",fontWeight:600,fontSize:11}}>⟲ Home</button></div></div>
    <div style={{width:375,height:812,borderRadius:44,background:C.white,boxShadow:"0 20px 60px rgba(0,0,0,0.15)",overflow:"hidden",display:"flex",flexDirection:"column",position:"relative"}}><div style={{position:"absolute",top:0,left:"50%",transform:"translateX(-50%)",width:160,height:30,background:"#000",borderRadius:"0 0 20px 20px",zIndex:10}}/><div style={{height:30}}/><StatusBar/><div style={{flex:1,display:"flex",flexDirection:"column",overflow:"hidden"}}>{R()}</div>{showNav&&<BottomNav active={tab} go={go}/>}<div style={{display:"flex",justifyContent:"center",paddingBottom:8,paddingTop:4}}><div style={{width:134,height:5,borderRadius:3,background:"#000",opacity:0.2}}/></div></div>
    <div style={{marginTop:8,fontSize:11,color:"#9CA3AF"}}>39 pantallas · Jorge Arturo Ruelas Mejía · Equipo 5</div>
  </div>);
}
